name: Windows NSIS Installer

on:
  push:
    branches:
      - master
      - 'Stable*'
    tags:
      - 'v*'
    paths-ignore:
      - 'docs/**'
  pull_request:
    paths:
      - '.github/workflows/windowsNSIS.yml'
      - 'deploy/windows/**'
      - 'src/**'
      - 'CMakeLists.txt'
      - 'cmake/**'

jobs:
  build-installer:
    runs-on: windows-latest
    defaults:
      run:
        shell: powershell

    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1
          fetch-tags: true

      # Install dependencies
      - name: Install NSIS
        run: choco install nsis -y

      - name: Install CMake
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

      - name: Install Ninja
        run: choco install ninja -y

      # Configure and build project
      - name: Configure Project
        run: |
          mkdir build
          cd build
          cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release

      - name: Build Project
        run: |
          cd build
          cmake --build . --config Release --parallel

      # Build NSIS installer
      - name: Build Windows Installer
        run: |
          & "C:\Program Files (x86)\NSIS\makensis.exe" deploy/windows/QGroundControlInstaller.nsi

      # Upload installer artifact (grabs any exe in deploy/windows)
      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: AMarinerControl-Installer
          path: deploy/windows/*.exe
