name: Windows NSIS Installer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt (MSVC 64-bit)
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.8.3
          host: windows
          target: desktop
          arch: win64_msvc2019_64
          cache: true

      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release ..

      - name: Build
        run: |
          cd build
          cmake --build . --config Release

      - name: Run NSIS
        run: |
          "C:\Program Files (x86)\NSIS\makensis.exe" deploy/windows/QGroundControlInstaller.nsi

          
      # Upload installer artifact (grabs any exe in deploy/windows)
      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: AMarinerControl-Installer
          path: deploy/windows/*.exe
